export const allWorks = [
  {
    id: 0,
    picture: '/img/works/Freedom_bank.webp',
    video: '/img/home/works/Freedomfinance.webm',
    slug: 'freedom-finance',
    name: 'Freedom Finance',
    tags: ['Brand Identity', 'Product Design'],
    isReady: true,
  },
  {
    id: 1,
    picture: '/img/works/vodafone/gallery1-3poster.jpg',
    video: '/img/works/vodafone/gallery1-3.webm',
    slug: 'vodafone',
    name: 'Vodafone',
    tags: ['Campaign Design', 'Motion'],
    isReady: true,
  },
  {
    id: 2,
    picture: '/img/works/Cruz.webp',
    video: '/img/home/works/Cruz.webm',
    slug: 'cruz',
    name: 'Cruz',
    tags: ['Product Design', 'Branding', 'Motion'],
    isReady: true,
  },
  {
    id: 3,
    picture: '/img/works/Freedom_cards.webp',
    slug: 'freedom-finance_card-series',
    name: 'Freedom Finance — Card series',
    tags: ['3D Motion'],
    isReady: true,
  },
  {
    id: 4,
    picture: '/img/works/NVO.webp',
    slug: 'nvo',
    name: 'NVO',
    tags: ['Brand Identity', 'Web Design'],
    isReady: true,
  },
  {
    id: 5,
    picture: '/img/works/nobleblocks.webp',
    video: '/img/home/works/Nobleblocks.webm',
    slug: 'nobleblocks',
    name: 'Nobleblocks',
    tags: ['Product Design', 'Branding', 'Motion'],
    isReady: true,
  },
  {
    id: 6,
    picture: '/img/works/looksrare.webp',
    video: '/img/home/works/Looksrare.webm',
    slug: 'looksrare',
    name: 'Looksrare',
    tags: ['Product Design', 'Branding', 'Motion'],
    isReady: true,
  },
  {
    id: 7,
    picture: '/img/works/ApeAi.webp',
    video: '/img/home/works/ApeAi.webm',
    slug: 'ape-ai',
    name: 'Ape AI',
    tags: ['Product Design', 'Branding'],
    isReady: false,
  },
  {
    id: 8,
    picture: '/img/works/Pancakeswap.webp',
    video: '/img/works/Pancakeswap.webm',
    slug: 'pancakeswap',
    name: 'Pancakeswap',
    tags: ['Product Design', 'Branding', 'Motion'],
    isReady: false,
  },
  {
    id: 9,
    picture: '/img/works/Ape_badges.webp',
    slug: 'ape-ai-achivement-badges',
    name: 'Ape AI — Achievement Badges',
    tags: ['Illustration', 'Branding'],
    isReady: false,
  },
  {
    id: 11,
    picture: '/img/works/Velas.webp',
    slug: 'velas',
    name: 'Velas',
    tags: ['Brand Identity', 'Product Design ', 'Motion'],
    isReady: false,
  },
  {
    id: 10,
    picture: '/img/works/Pancake.webp',
    video: '/img/works/Pancake.webm',
    slug: 'pancake',
    name: 'Pancake',
    tags: ['3D Motion', 'Illustration'],
    isReady: false,
  },
  {
    id: 12,
    picture: '/img/works/Pranzo.webp',
    slug: 'pranzo',
    name: 'Pranzo',
    tags: ['Brand Identity', 'Motion Design'],
    isReady: false,
  },
  {
    id: 13,
    picture: '/img/works/Tama.webp',
    video: '/img/home/Tama.webm',
    slug: 'tama',
    name: 'Tama',
    tags: ['Product Design', 'Branding'],
    isReady: false,
  },
  {
    id: 14,
    picture: '/img/works/Eclipse_Parlays_fun.webp',
    slug: 'eclipse',
    name: 'Eclipse — Parlays fun',
    tags: ['Illustration', '3D Motion'],
    isReady: false,
  },
  {
    id: 15,
    picture: '/img/works/Polkadot.webp',
    slug: 'polkadot',
    name: 'Polkadot',
    tags: ['Campaign Design', 'Motion Design'],
    isReady: false,
  },
  {
    id: 16,
    picture: '/img/works/Boba.webp',
    slug: 'bobaswap',
    name: 'Bobaswap',
    tags: ['Illustration', 'Branding', 'Motion'],
    isReady: false,
  },
  {
    id: 17,
    picture: '/img/works/NFT.webp',
    slug: 'nft-collections',
    name: 'NFT Collections',
    tags: ['Illustration', 'Art Direction'],
    isReady: false,
  },

]

export function getWorksByCategory(category) {
  if (category === 'all') {
    return allWorks
  }

  console.log(category)

  return allWorks.filter((item) => item.tags.includes(category))
}
